action: Improve retrieve-comment failure handling

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -543,12 +543,18 @@ runs:
         if [ ! -s artifact.zip ]; then
           gh_api_out=$(mktemp)
           gh_api_err=$(mktemp)
-          if ! gh api "/repos/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID/artifacts?per_page=1" > "$gh_api_out" 2> "$gh_api_err"; then
-            if grep -q 'HTTP 403' "$gh_api_err"; then
-              act-summary
-              (
-                echo '# Workflow is missing permissions'
-                echo 'Please add `actions: read` to enable check-spelling to retrieve the artifact it needs to post a comment. [more info](https://docs.check-spelling.dev/Workflow-Permissions#actions-read)'
+          canary=$(mktemp)
+          (
+            if ! gh api "/repos/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID/artifacts?per_page=1" > "$gh_api_out" 2> "$gh_api_err"; then
+              if grep -q 'HTTP 403' "$gh_api_err"; then
+                act-summary
+                if grep -q '#rate-limiting' "$gh_api_out"; then
+                  echo '# GitHub Rate limit hit'
+                  echo 'This generally happens when a repository triggers too many workflows in a short period of time. An admin or owner can rerun this workflow if necessary. Sorry about that.'
+                else
+                  echo '# Workflow is missing permissions'
+                  echo 'Please add `actions: read` to enable check-spelling to retrieve the artifact it needs to post a comment. [more info](https://docs.check-spelling.dev/Workflow-Permissions#actions-read)'
+                fi
                 echo
                 echo '#### Technical details'
                 echo '```'
@@ -556,9 +562,14 @@ runs:
                 cat "$gh_api_out"
                 echo
                 echo '```'
-              ) >> "$GITHUB_STEP_SUMMARY"
+                rm "$canary"
+              fi
             fi
-          fi
+            if [ -e "$canary" ]; then
+              echo '#### Could not find artifact'
+              echo "Artifact retrieval failed, please check the list of [known issues](https://github.com/check-spelling/check-spelling/issues?q=is%3Aissue%20retrieve-comment) and [file an issue](https://github.com/check-spelling/check-spelling/issues/new?title=%60retrieve-comment%60%20scenario&body=Please%20provide%20details+preferably%20including%20a%20link%20to%20a%20workflow%20run,%20the%20configuration%20of%20the%20repository,%20and%20anything%20else%20you%20may%20know%20about%20the%20problem%2e) if you can't find a related issue."
+            fi
+          ) >> "$GITHUB_STEP_SUMMARY"
           echo "no-comment=1" >> "$GITHUB_OUTPUT"
         fi
     - name: check-spelling
