gh-run-download: Fix comment retrieval
- refactor run download to a script
- replace `gh run download` because the endpoint is broken
  https://api.github.com/repos/cli/cli/issues/12437

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -539,28 +539,27 @@ runs:
         suffix: ${{ inputs.report_title_suffix }}
       run: |
         : Retrieve comment
-        if ! gh run download -R "$GITHUB_REPOSITORY" "$GITHUB_RUN_ID" -n "check-spelling-comment-$suffix" 2>/dev/null; then
-          if ! gh run download -R "$GITHUB_REPOSITORY" "$GITHUB_RUN_ID" -n check-spelling-comment 2>/dev/null; then
-            gh_api_out=$(mktemp)
-            gh_api_err=$(mktemp)
-            if ! gh api "/repos/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID/artifacts?per_page=1" > "$gh_api_out" 2> "$gh_api_err"; then
-              if grep -q 'HTTP 403' "$gh_api_err"; then
-                act-summary
-                (
-                  echo '# Workflow is missing permissions'
-                  echo 'Please add `actions: read` to enable check-spelling to retrieve the artifact it needs to post a comment. [more info](https://docs.check-spelling.dev/Workflow-Permissions#actions-read)'
-                  echo
-                  echo '#### Technical details'
-                  echo '```'
-                  cat "$gh_api_err"
-                  cat "$gh_api_out"
-                  echo
-                  echo '```'
-                ) >> "$GITHUB_STEP_SUMMARY"
-              fi
+        "$spellchecker/gh-run-download.sh"
+        if [ ! -s artifact.zip ]; then
+          gh_api_out=$(mktemp)
+          gh_api_err=$(mktemp)
+          if ! gh api "/repos/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID/artifacts?per_page=1" > "$gh_api_out" 2> "$gh_api_err"; then
+            if grep -q 'HTTP 403' "$gh_api_err"; then
+              act-summary
+              (
+                echo '# Workflow is missing permissions'
+                echo 'Please add `actions: read` to enable check-spelling to retrieve the artifact it needs to post a comment. [more info](https://docs.check-spelling.dev/Workflow-Permissions#actions-read)'
+                echo
+                echo '#### Technical details'
+                echo '```'
+                cat "$gh_api_err"
+                cat "$gh_api_out"
+                echo
+                echo '```'
+              ) >> "$GITHUB_STEP_SUMMARY"
             fi
-            echo "no-comment=1" >> "$GITHUB_OUTPUT"
           fi
+          echo "no-comment=1" >> "$GITHUB_OUTPUT"
         fi
     - name: check-spelling
       id: spelling
