Remove trailing `.` from messages
Sarif.t: Require rule messages not to have trailing `.`

check-dictionary: Reword `unexpected-line-ending`
CheckDictionary: Reword `non-alpha-in-dictionary`
CheckPattern: Reword `bad-regex`
SpellingCollator: Reword `check-file-path`
SpellingCollator: Reword `unrecognized-spelling`
summary-tables: Reword `summary-table-error`
unknown-words: Reword `missing-on-pull-request-event`
unknown-words: Reword `no-newline-at-eof`
unknown-words: Reword `summary-table-skipped`
unknown-words: Reword `unsupported-configuration`
unknown-words: Reword `unsupported-repo-notation`
UnknownWordSplitter: Reword `binary-file`
UnknownWordSplitter: Reword `forbidden-pattern`
UnknownWordSplitter: Reword `large-file`
UnknownWordSplitter: Reword `minified-file`
UnknownWordSplitter: Reword `single-line-file`
UnknownWordSplitter: Reword `slow-file`
UnknownWordSplitter: Reword `token-is-substring`
UnknownWordSplitter: Reword `utf16-surrogate-file`

diff --git a/wrappers/summary-tables b/wrappers/summary-tables
--- a/wrappers/summary-tables
+++ b/wrappers/summary-tables
@@ -1,5 +1,5 @@
 #!/bin/sh
 if ! timeout 120s /usr/bin/env -S perl -T -I"$spellchecker/lib" "$spellchecker/summary-tables.pl" "$@"; then
   echo ":frowning: Failed to build summary tables, if you cannot find a bug about this, please file one (summary-tables-error)"
-  echo "::warning title=Summary Table failed::Details too big to include in Step Summary. (summary-table-error)" >&2
+  echo "::warning title=Summary Table failed::Details too big to include in Step Summary (summary-table-error)" >&2
 fi
