test.yml: Download jd instead of building it

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -45,6 +45,8 @@ jobs:
         required_perl_modules: ${{ steps.perl-config.outputs.perl-modules }}
         GH_TOKEN: ${{ github.token }}
       run: |
+        PATH="$PATH":~/go/bin
+        mkdir -p ~/go/bin
         (
           PATH=$PATH:~/go/bin
           cpan_modules=$(
@@ -55,8 +57,6 @@ jobs:
           command -v cover >/dev/null 2>/dev/null || APT_PACKAGES=libdevel-cover-perl
           [ -z "$cpan_modules" ] || command -v cpanm >/dev/null 2>/dev/null || curl -s -S -L https://cpanmin.us | perl - --sudo App::cpanminus
           command -v jd && HAS_JD=1 || HAS_JD=
-          [ -n "$HAS_JD" ] || command -v go >/dev/null 2>/dev/null || GO_PACKAGE=" golang"
-          APT_PACKAGES="$APT_PACKAGES$GO_PACKAGE"
           [ -z "$APT_PACKAGES" ] ||
           (
             sudo apt-get install -y $APT_PACKAGES ||
@@ -64,7 +64,12 @@ jobs:
             sudo apt-get install -y $APT_PACKAGES
           )
           [ -z "$cpan_modules" ] || perl `command -v cpanm` -S --notest $cpan_modules
-          [ -n "$HAS_JD" ] || go install 'github.com/josephburnett/jd@latest' || echo 'Could not install jd' >&2
+          if [ -z "$HAS_JD" ]; then
+            JD_BIN=~/go/bin/jd
+            gh release download -R josephburnett/jd -p "*$(go env GO"ARCH")-$(go env GO"OS")*" -O "$JD_BIN" &&
+            chmod +x "$JD_BIN" ||
+            echo 'Could not install jd' >&2
+          fi
         ) > /tmp/prework || (cat /tmp/prework && false)
         ./Build.PL
         ./Build build
